### ISSUE TITLE
On width_to_focal

### ISSUE THREAD

**Issue by kingsleyluoxin** [ClementPinard/unsupervised-depthnet#2]
Hi, i have some puzzle about the codes to convert disparity to depth.
width_to_focal[1242] = 721.5377. width_to_focal[1241] = 718.856. width_to_focal[1224] = 707.0493. width_to_focal[1238] = 718.3351
I wonder where to find these parameters. Are they in calibration files? 
Thanks

**Comment by ClementPinard** [comment]
yes, they are in calibration files.
Each scene in KITTI raw has a `calib_cam_to_cam.txt` where the `P_rect` matrix says what are the fx and fy focal lengths. Turns out that it's actually linked to image size.

As a consequence, it is hardwritten to save code for reading calib files.

This piece of code originates from godart's repo that you can see here : https://github.com/mrharicot/monodepth/blob/master/utils/evaluation_utils.py#L29

**Comment by kingsleyluoxin** [comment]
Thanks a ton for your reply!
